# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pytest-record-replay',
                'doc_host': 'https://CharlesFauman.github.io',
                'git_url': 'https://github.com/CharlesFauman/pytest-record-replay',
                'lib_path': 'pytest_record_replay'},
  'syms': {'pytest_record_replay.core': {'pytest_record_replay.core.foo': ('core.html#foo', 'pytest_record_replay/core.py')}}}
